
title: Motor Control
author: Hillary Cornell Hoyt
email: hoyt.h@northeastern.edu
description: >
  Motor Control
  
twitter_username: hillarychoyt
github_username:  hillarychoyt
linkedin_username: hillarychoyt

theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemapâ€©
