
title: Motor Control
author: Hillary Cornell Hoyt
email: hoyt.h@northeastern.edu
description: >
  Motor Control
  
twitter_username: hoyt_hillary
github_username:  hillaryhoyt
linkedin_username: hchoyt

theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemapâ€©
