
title: Recipes and Book Reviews
author: Hillary C Hoyt
description: >
  What I've been up to
  
github_username:  hillarychoyt
linkedin_username: hillarychoyt

theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemapâ€©
